### ISSUE TITLE
[BUG] no usleep while compiling using gcc-9.1 or Intel Compiler

### ISSUE THREAD

**Issue by zhum** [lammps/lammps#1880]
**Summary**

After `git clone -b stable https://github.com/lammps/lammps.git` I do: `cd src; make yes-manybody; make gpu`. Then I get this error:
```
../variable.cpp: In member function ‘int LAMMPS_NS::Variable::next(int, char**)’:
../variable.cpp:677:7: error: ‘usleep’ was not declared in this scope; did you mean ‘sleep’?
```
I use CUDA-10.1, GCC-9.1, openmpi/4.0.1. If I try to use Intel Compiler (15, 2017 or 2019), I get the same error (other words, but the same meaning).

**LAMMPS Version and Platform**

LAMMPS from git, branch `stable` (14.02.2020). Intel Xeon E5-2697 v3, Linux Centos 7.5.

**Expected Behavior**

Succesfull compilation.

**Actual Behavior**

Compiler error - no usleep function.

**Steps to Reproduce**

`git clone -b stable https://github.com/lammps/lammps.git && cd lammps/src; make yes-manybody; make gpu`

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
Thanks for the report, but this sounds more like there may be something wrong with your Linux installation. We compile LAMMPS regularly with gcc 9.x (e.g. version 9.2.1 on Fedora 31) and the intel compiler as well as on CentOS 7.x (but with the "native" gcc 4.8.x compiler) and have never seen this. Also, this piece of code has been around for quite some time (over 6 years), so if there was something non-portable about this, it would have surfaced then. Since you report an unusual combination of tools, those have to be custom installed, and thus it is most likely, that something went wrong in that process, or that there is something other happening on your machine like file system corruption, that renders the system header files being pulled in for your compilation incompatible.

**Comment by zhum** [comment]
Hm... I don't know why it worked. My investigations show:

/usr/include/features.h:
```
/* If _GNU_SOURCE was defined by the user, turn on all the other features.  */
#ifdef _GNU_SOURCE
//...
# define _POSIX_C_SOURCE        200809L
# undef  _XOPEN_SOURCE
# define _XOPEN_SOURCE  700

//...

#ifdef  _XOPEN_SOURCE
# define __USE_XOPEN    1
# if (_XOPEN_SOURCE - 0) >= 500
#  define __USE_XOPEN_EXTENDED  1
#  define __USE_UNIX98  1
#  undef _LARGEFILE_SOURCE
#  define _LARGEFILE_SOURCE     1
#  if (_XOPEN_SOURCE - 0) >= 600
#   if (_XOPEN_SOURCE - 0) >= 700
#    define __USE_XOPEN2K8      1
//      ^^^^^^^^^^^^^^^^^^^^^!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Then /usr/include/unistd.h:
```
#if (defined __USE_XOPEN_EXTENDED && !defined __USE_XOPEN2K8) \
    || defined __USE_BSD
//...
extern int usleep (__useconds_t __useconds);
#endif
```

_GNU_SOURCE is defined on Linux systems (by gcc internals) by default. So __USE_XOPEN2K8 would be defined too. And then condition in unistd.h should not work.
I "fixed" this by adding
```
#undef __USE_XOPEN2K8
```
before `#include <unistd.h>` in variables.cpp, but it seems to be a dirty hack. May be you should use nanosleep or something else if __USE_XOPEN2K8 is defined?

**Comment by akohlmey** [comment]
Sorry, but you are looking at the wrong define.

Using `-D_GNU_SOURCE` will include `-D_BSD_SOURCE` (on centos 7) or `-D_DEFAULT_SOURCE` (on newer systems), which will in turn define `__USE_BSD` or `__USE_MISC`, respectively. And because of the `||` clause in the unistd.h header that should include the prototype of `usleep()`.

Either you are using very unusual compiler/preprocessor flags (perhaps directly, perhaps indirectly) or have some incompatible header files that clash with the standard headers somewhere in your include path or modify the expected settings, or there is something corrupted or incorrectly installed on your machine.

I suggest you try again with a clean CentOS 7 install (if you have the singularity container software installed, it can be as simple as:
`singularity pull library://lammps/default/lammps_development:centos:7`
). Check out the `tools/singularity` folder in the current LAMMPS development version for container definitions and images that have been tested for compiling/debugging LAMMPS.
And then provide here the exact steps necessary to reproduce the failing compilation in that container image (or pick one of the other options, if necessary).

**Comment by akohlmey** [comment]
@zhum have you been able to reproduce the compilation failure with a "clean" Linux installation/container or have you identified the compilation flags/settings or header conflicts that was causing your compilations to fail contrary to our integration tests on the same kind of OS/compiler choice?

I've done a bit more research and it seems a good idea to have LAMMPS become less dependent on APIs like `usleep()` that are common, but considered obsolete and should be replaced and just submitted a feature request issue on that topic that will hopefully start a discussion within the LAMMPS developers to increase portability and maintainability in the long run. So thanks for pointing out this issue, even though it should not yet be a problem, but could become one in the future.

**Comment by akohlmey** [comment]
@zhum if there are no further updates showing how we can reproduce this issue, this will be closed as invalid assuming that your installation is at fault.

**Comment by zhum** [comment]
I'm AFK for 2 weeks, but after 9-th march I'll try to compile LAMMPS inside a container. And try to figure out why it cannot be  compiled on my installation. I'll write my results here.

**Comment by akohlmey** [comment]
@zhum any updates?

**Comment by zhum** [comment]
I've compiled it successfully with gcc-4.8.5 and cuda-8 (openmpi-4.0.1). But with newer gcc versions it fails.
Works for now, but please check compilation with modern gcc/cuda.

**Comment by akohlmey** [comment]
Sorry, but the problem **must** be with your installation. We compile LAMMPS regularly on machines with newer GCC installations and have never seen a failure like you describe it.

However, the configuration your report is not supported. When I try to compile code with CUDA 10.2 on Fedora 31, which ships with gcc 9.2, I get this error:
```
In file included from /usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
```
I have to install a custom gcc 8 to make this work. Thus I will declare this now an invalid bug report and close this issue.

**Comment by zhum** [comment]
New version does not work with gcc-8.0.
- cmake/3.19.8
- cuda/10.1
- openmpi/4.1.0-gcc 
- gcc/8.0

```
cd src; make yes-manybody; make gpu
....
In file included from ../nstencil_half_multi_2d.cpp:21:
/opt/rh/devtoolset-8/root/usr/include/c++/8/math.h:65:12: error: ‘constexpr bool std::isinf(double)’ conflicts with a previous declaration
 using std::isinf;
            ^~~~~
In file included from /opt/cuda/cuda-10.1/include/features.h:377,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/x86_64-redhat-linux/bits/os_defines.h:39,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/x86_64-redhat-linux/bits/c++config.h:2452,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/cstdint:38,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/cinttypes:38,
                 from ../lmptype.h:45,
                 from ../pointers.h:25,
                 from ../nstencil.h:17,
                 from ../nstencil_half_multi_2d.h:24,
                 from ../nstencil_half_multi_2d.cpp:15:
/usr/include/bits/mathcalls.h:202:1: note: previous declaration ‘int isinf(double)’
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^~~~~~~~~~~~
In file included from ../nstencil_half_multi_2d.cpp:21:
/opt/rh/devtoolset-8/root/usr/include/c++/8/math.h:66:12: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
 using std::isnan;
            ^~~~~
In file included from /opt/cuda/cuda-10.1/include/features.h:377,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/x86_64-redhat-linux/bits/os_defines.h:39,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/x86_64-redhat-linux/bits/c++config.h:2452,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/cstdint:38,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/cinttypes:38,
                 from ../lmptype.h:45,
                 from ../pointers.h:25,
                 from ../nstencil.h:17,
                 from ../nstencil_half_multi_2d.h:24,
                 from ../nstencil_half_multi_2d.cpp:15:
/usr/include/bits/mathcalls.h:235:1: note: previous declaration ‘int isnan(double)’
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^~~~~~~~~~~~
        make[1]: *** [Makefile:109: nstencil_half_multi_2d.o] Error 1
```

**Comment by akohlmey** [comment]
This looks like an issue with your environment. Why does GCC include a CUDA toolkit header when compiling regular C++ code and not CUDA code? 
Your C++ compiler includes the os_defines.h header that includes the "features.h" header, which should include /usr/include/features.h (as bundled with glibc), but instead it picks up /opt/cuda/cuda-10.1/include/features.h

...and I looked up all my CUDA installations (from cuda 7.5 to 11.3) and **none** of them does have that specific include file.
So we are back to the situation that you reported before, and that is that you have a tainted installation.

**Comment by zhum** [comment]
It seems to be an odd cuda installation file... Reinstall did not help - this file was installed, but after renaming this file compilation was succesfsul.

P.S. It would be fine to add detailed pre-requisites with supported gcc, intel, gpi, cuda versions.

**Comment by akohlmey** [comment]
It is next to impossible to provide those detailed version Infos. The core
LAMMPS code can be compiled with pretty much any compiler that supports
C++11. Additional limitations come into play when optional packages are
installed. KOKKOS requires C++14, and has limits to what CUDA versions it
supports, CUDA itself has limits as to which GCC or Clang or Intel compiler
it supports and those change with the CUDA version. The GPU package
supports all CUDA versions down to 3.x, but there are all kinds of limits
with GPU hardware and driver etc.

We continually test compilation on a variety of Linux versions and
compilers from CentOS 7, over Ubuntu 18.04 and 20.04, to Fedora 32, 33, and
34. As well as MacOS 11 and windows with MinGW compilers.

All indicators point to the origin of your problems being caused by
misconfiguration or incorrect modifications or installation of software and
tools on your system. Given the large number of deployments of LAMMPS, any
significant issues on the LAMMPS side would be detected and reported
quickly by multiple people, but that is currently not the case.

The most common portability/compatibility issues are on Non-Linux platforms
like MacOS, Windows and FreeBSD.

--
Dr. Axel Kohlmeyer ***@***.*** http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste, Italy
