### PR TITLE
Fixes various compilation issues

### LINKED ISSUE #1076: LAMMPS triggers compiler warnings
## Summary

LAMMPS triggers a whole bunch of compiler warnings and errors when built with pedantic comnpile options, such as `-Wreorder`, `-Wunused-parameter`, etc.

## Type of Issue

Suggestion for enhancement.

## Detailed Description (Enhancement Suggestion)

We are looking into building LAMMPS integrated with an application based on the MOOSE framework (https://mooseframework.org) using our build system, which has lots of warning flags turned on by default. I believe compiler warnings are a valuable tool that can help uncover real code issues, but that only works if you strive to keep you build clean of warnings in the first place. 

## LAMMPS Version (Bug Report)

Current HEAD

## Expected Behavior (Bug Report)

LAMMPS should build without any compile warnings (if warnings are turned on)

## Actual Behavior (Bug Report)

Warnings flood the screen (a large fraction coming from unused parameters in `memory.h`), then the build fails with out of order member initialization:

```
/Users/schwd/Programs/lammps/src/memory.h:549:60: warning: unused parameter 'n3' [-Wunused-parameter]
  TYPE ******create(TYPE ******&array, int n1, int n2, int n3, int n4,
                                                           ^
/Users/schwd/Programs/lammps/src/memory.h:549:68: warning: unused parameter 'n4' [-Wunused-parameter]
  TYPE ******create(TYPE ******&array, int n1, int n2, int n3, int n4,
                                                                   ^
/Users/schwd/Programs/lammps/src/memory.h:550:25: warning: unused parameter 'n5' [-Wunused-parameter]
                    int n5, const char *name)
                        ^
/Users/schwd/Programs/lammps/src/fix_neigh_history.cpp:38:38: error: field 'valuepartner' will be initialized after field 'pair' [-Werror,-Wreorder]
  npartner(__null), partner(__null), valuepartner(__null), pair(__null),
                                     ^
/Users/schwd/Programs/lammps/src/fix_neigh_history.cpp:689:53: warning: unused parameter 'delflag' [-Wunused-parameter]
void FixNeighHistory::copy_arrays(int i, int j, int delflag)
                                                    ^
60 warnings and 1 error generated.
```

## Steps to Reproduce (Bug Report)

build with `-Werror=return-type -Werror=reorder -Woverlength-strings -Wunused`

**I'll be working on a patch to fix some of this issues (as far as I consider them issues at least)**

### PR DESCRIPTION
**Pull request by rbberger**
## Purpose
- fixes a compilation issue introduced by #1077, due to conditional compilation such as `-DLMP_USER_OMP`
- add missing `LMP_USER_OMP` definition to CMake build which was exposed by fixing this
- add missing `domain_omp.cpp`
- cleans up `accelerator_omp.h`
- add additional space to avoid code highlighting issues

closes #1076 

## Author(s)

@rbberger

## Backward Compatibility

yes

## Implementation Notes

Added `LMP_UNUSED_PARAM` macro to create empty statements to suppress unused parameter warnings and documenting that case at the same time.

**Usage:**
```cpp
#ifdef LMP_USER_OMP
   // only code path using variable x
#else
  LMP_UNUSED_PARAM(x);
#endif
```

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by junghans** [comment]
Couldn't you use the compiler internal `_OPENMP` define for that?

**Comment by akohlmey** [comment]
@junghans this issue depends on whether USER-OMP is installed, which is independent of whether OpenMP is enabled
