### ISSUE TITLE
[BUG] stable_23Jun2022_update4 fails to build with kokkos-4.0.01

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#3805]
**Summary**

```
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-stable_23Jun2022_update4/src/atom.cpp:17:
In file included from /wrkdirs/usr/ports/science/lammps/work/.build/styles/style_atom.h:2:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-stable_23Jun2022_update4/src/KOKKOS/atom_vec_angle_kokkos.h:26:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-stable_23Jun2022_update4/src/KOKKOS/atom_vec_kokkos.h:20:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-stable_23Jun2022_update4/src/KOKKOS/kokkos_type.h:24:
/usr/local/include/Kokkos_Vectorization.hpp:21:1: error: static_assert failed "Including non-public Kokkos header files is not allowed."
static_assert(false,
^             ~~~~~
1 error generated.
```

FreeBSD 13.2

**Comment by stanmoore1** [comment]
@yurivict thanks for letting us know, will take a look

**Comment by akohlmey** [comment]
@yurivict Please note that achieving forward compatibility is extremely difficult, specifically with major version updates. The 23Jun2022 version bundles and was tested with Kokko 3.6.x, so trying to make it work with Kokkos v4.0.x is asking for a *lot*.

You should always be able to use the bundled Kokkos library instead of an external one. Also, the current feature release version, 28 March 2023 (which bundles Kokkos 3.7.x), has been adjusted to also be compatible with (current) Kokkos 4.0.x versions. We are planning to have a new stable release soon and update 4 is the last update for last year's stable version.

After looking at the affected source code, it looks like Kokkos 4.0 has an option `-DKokkos_ENABLE_DEPRECATED_CODE_3=on` that may make it compatible with software that was developed for a Kokkos 3.x version.

**Comment by yurivict** [comment]
Ok, thanks.

I will switch to the current feature release then.

**Comment by akohlmey** [comment]
@yurivict Did using the feature release work for you? Can we close this issue?

**Comment by yurivict** [comment]
I will try the feature release.

Thank you.
