### ISSUE TITLE
[BUG] USER-PTM compilation broken

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#1600]
**Summary**

Due to the missing inclusion of a standard header NULL is not defined in GCC 4.8.5 (CentOS 7). 

PR #1599 addresses this.

**LAMMPS Version and Platform**

current master

**Expected Behavior**

Working compilation.

**Actual Behavior**

```
In file included from src/USER-PTM/ptm_alloy_types.h:13:0,
                 from src/USER-PTM/ptm_index.cpp:10:
src/USER-PTM/ptm_initialize_data.h:52:41: error: ‘NULL’ was not declared in this scope
                                         NULL,                                //.points_alt1
                                         ^
src/USER-PTM/ptm_initialize_data.h:53:41: error: ‘NULL’ was not declared in this scope
                                         NULL,                                //.points_alt2
                                         ^

```

**Steps to Reproduce**

Compile with GCC 4.8.5 on CentOS 7.

**Comment by akohlmey** [comment]
fixed by merging #1599
