### ISSUE TITLE
Failed compile due to lmpinstalledpkgs.h

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#1284]
## Summary

I sometimes build two versions of LAMMPS at the same time using gmake for debugging purposes. This now fails due to #899 because the lmpinstalledpkgs.h file gets messed up. The concurrent builds somehow collide:

```
In file included from ../lammps.cpp:54:0:
../lmpinstalledpkgs.h:4:2: error: #endif without #if
 #endif
  ^~~~~
```

Here is the contents of the messed up lmpinstalledpkgs.h file:

```
"KOKKOS",
"SNAP",
 NULL };
#endif
```

Can this file be moved to the `obj` directory and be generated separately for each build?

## Type of Issue

Bug report

## LAMMPS Version (Bug Report)

Latest master since #899.

## Expected Behavior (Bug Report)

Separate builds don't collide like in the past.

**Comment by akohlmey** [comment]
This is not a supported mode for the conventional build (and never has been). lmpinstalledpkgs.h is not the only file that can get corrupted while launching multiple concurrent makes. i have run into that a few times in the past. i would suggest to use CMake instead. or do "make  -j# arch1 && make -j# arch2", but *not* "make -j# arch1 arch2"

**Comment by stanmoore1** [comment]
It seems like since the conventional build system uses separate `obj` directories and separate `exe` files, this should be trivial to fix.

**Comment by akohlmey** [comment]
> I'm using make -j# arch1 on one terminal window and make -j# arch2 on a second terminal window. What other files get corrupted?

They don't always get corrupted, but all the style_xxx.h files use the same mechanism, only the window for corrupting race conditions is smaller than for lmpinstalledpkgs.h.

**Comment by akohlmey** [comment]
> It seems like since the conventional build system uses separate `obj` directories and separate `exe` files, this should be trivial to fix.

it is not as trivial as you might think, you need to have a per-instance unique temporary filenames generated in a platform portable way. it gets even more complicated when you have a folder shared between multiple machines on a networked file system. using CMake enforces proper out-of-source builds and thus avoids the issue by construction. same is true for "make -j# arch1 && make -j# arch2" just crank up the '#' and it would be about the same combined speed. '#' is often optimal when chose a bit larger than the available number of physical CPU cores, BTW.

**Comment by akohlmey** [comment]
Let me try to address this from the other end: is there something that you cannot do with CMake, but with the conventional build? or something where CMake is inconvenient to use? The CMake build system has come so close to be able to replace the conventional build system, that i would rather spend time on make it a complete replacement, than trying to improve the old build system.

**Comment by stanmoore1** [comment]
Why can't these files be generated when packages are installed/uninstalled and not at compile time? When I'm compiling I'm not changing the packages, so `lmpinstalledpkgs.h` doesn't need to be regenerated every time. Same with the style files.

**Comment by akohlmey** [comment]
> Why can't these files be generated when packages are installed/uninstalled and not at compile time? When I'm compiling I'm not changing the packages, so `lmpinstalledpkgs.h` doesn't need to be regenerated every time. Same with the style files.

in the conventional build, packages and style files may have been added or removed by other means than "make yes-pkg" or "make no-pkg".

CMake currently fails to detect newly added/removed sources, e.g. when i add a new style file, or when i switch between branches that have files added or removed. see #1278 
the conventional make can handle this **exactly** because it attempts to update the style files every time (but only does so, if there are changes).

**Comment by stanmoore1** [comment]
>>it is not as trivial as you might think, you need to have a per-instance unique temporary filenames generated in a platform portable way. 

Why does it need to be per-instance? Couldn't we just append the `exe` name, like `mpi` or `serial` from `Makefile.mpi` or `Makefile.serial`.

**Comment by stanmoore1** [comment]
>How about this

Thanks, I'll give it a whirl.

**Comment by akohlmey** [comment]
> I can't use "make -j# arch1 && make -j# arch2" because I'm on two different machines with a shared file system. I'm changing src files and recompiling and comparing output. So I need two different terminal windows.

Shared networked file systems can create all kinds of race condition problems. If the hack from above fixes it, i am willing to include it. But i would regardless advise to give building with CMake a try. out of source builds is a strength of that system, and that extends into the lib folder, where only KOKKOS (due to some ultra-extreme gmake hacking) works around. If we had not have CMake added, i would have tried to port the KOKKOS lib hack (to compile lib folder sources into a library under src/Obj_arch) to all lib targets, but - thankfully - that is no longer needed.
