### ISSUE TITLE
KOKKOS Cuda doesn't compile on mac

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#240]
I'm on Mac OSX 10.11.3 using clang-omp++ (changed architecture and compiler in lib/kokkos/config/nvcc_wrapper) using Cuda 7.5.

When I compile kokkos_cuda_openmpi (changed the CC and LINK to the wrapper), everything is fine until it reaches
```
/projects/lammps-30Jul16/lib/kokkos/config/nvcc_wrapper -g -O3 -fopenmp   -DLAMMPS_GZIP -DLMP_KOKKOS  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1 -I/usr/local/Cellar/open-mpi/1.10.1_1/include   -I./ -I../../lib/kokkos/core/src -I../../lib/kokkos/containers/src -I../../lib/kokkos/algorithms/src  --std=c++11 -arch=sm_30 -Xcompiler -fopenmp  -c ../image.cpp
```
where I get compilation error

```
../pair_buck_coul_cut_kokkos.h:120:17: error: no function template matches function template specialization 'pair_compute_neighlist'
friend EV_FLOAT pair_compute_neighlist< PairBuckCoulCutKokkos, HALF, void> (PairBuckCoulCutKokkos *, NeighListKokkos< DeviceType> *);
```

This happens with other pair style header files as well. I have tried the latest git version and the latest stable version.

Am I missing something or should this work?

**Comment by akohlmey** [comment]
KOKKOS is very sensitive to C++11 standard compliance. Please see lib/kokkos/README for supported compiler versions, but keep in mind, that MacOSX often ships with heavily modified compilers.

I use a special environment module on my (Fedora Linux) machine with a self-compiled GCC-4.9.3 for for GPU/CUDA and KOKKOS/CUDA compiles.

**Comment by andeplane** [comment]
Ahh ok, I see. 

If I compile with gcc (I tried both 4.8.5 and 6.2.0), I get
nvcc fatal   : GNU C/C++ compiler is no longer supported as a host compiler on Mac OS X.
so it then has to be intel compiler or clang I suppose. 

Note that the clang version I installed is not the one shipped with OSX, but from `brew install llvm`, version 3.5.0, whereas 3.5.2 is listed as tested in lib/kokkos/README.

**Comment by stanmoore1** [comment]
It should definitely compile with gcc or the intel compiler. I never use clang so it is possible that Kokkos LAMMPS has slightly non-c++-compliant code that gcc and intel overlook, it has happened in the past.

**Comment by stanmoore1** [comment]
See http://stackoverflow.com/questions/24345399/narrowing-int-to-bool-in-sfinae-different-output-between-gcc-and-clang. I believed I have fixed the issue:

Index: KOKKOS/pair_kokkos.h
===================================================================
--- KOKKOS/pair_kokkos.h        (revision 15814)
+++ KOKKOS/pair_kokkos.h        (working copy)
@@ -611,7 +611,7 @@
 // pair_compute_neighlist and pair_compute_fullcluster will match - either the dummy version
 // or the real one further below.
 template<class PairStyle, unsigned NEIGHFLAG, class Specialisation>
-EV_FLOAT pair_compute_neighlist (PairStyle* fpair, typename Kokkos::Impl::enable_if<!(NEIGHFLAG&PairStyle::EnabledNeighFlags), NeighListKokkos<typename PairStyle::device_type>*>::type list) {
+EV_FLOAT pair_compute_neighlist (PairStyle* fpair, typename Kokkos::Impl::enable_if<!((NEIGHFLAG&PairStyle::EnabledNeighFlags) != 0), NeighListKokkos<typename PairStyle::device_type>*>::type list) {
   EV_FLOAT ev;
   (void) fpair;
   (void) list;
@@ -620,7 +620,7 @@
 }

 template<class PairStyle, class Specialisation>
-EV_FLOAT pair_compute_fullcluster (PairStyle* fpair, typename Kokkos::Impl::enable_if<!(FULLCLUSTER&PairStyle::EnabledNeighFlags), NeighListKokkos<typename PairStyle::device_type>*>::type list) {
+EV_FLOAT pair_compute_fullcluster (PairStyle* fpair, typename Kokkos::Impl::enable_if<!((FULLCLUSTER&PairStyle::EnabledNeighFlags) != 0), NeighListKokkos<typename PairStyle::device_type>*>::type list) {
   EV_FLOAT ev;
   (void) fpair;
   (void) list;
@@ -630,7 +630,7 @@

 // Submit ParallelFor for NEIGHFLAG=HALF,HALFTHREAD,FULL,N2
 template<class PairStyle, unsigned NEIGHFLAG, class Specialisation>
-EV_FLOAT pair_compute_neighlist (PairStyle* fpair, typename Kokkos::Impl::enable_if<NEIGHFLAG&PairStyle::EnabledNeighFlags, NeighListKokkos<typename PairStyle::device_type>*>::type list) {
+EV_FLOAT pair_compute_neighlist (PairStyle* fpair, typename Kokkos::Impl::enable_if<(NEIGHFLAG&PairStyle::EnabledNeighFlags) != 0, NeighListKokkos<typename PairStyle::device_type>*>::type list) {
   EV_FLOAT ev;
   if(fpair->atom->ntypes > MAX_TYPES_STACKPARAMS) {
     PairComputeFunctor<PairStyle,NEIGHFLAG,false,Specialisation > ff(fpair,list);
@@ -646,7 +646,7 @@

 // Submit ParallelFor for NEIGHFLAG=FULLCLUSTER
 template<class PairStyle, class Specialisation>
-EV_FLOAT pair_compute_fullcluster (PairStyle* fpair, typename Kokkos::Impl::enable_if<FULLCLUSTER&PairStyle::EnabledNeighFlags, NeighListKokkos<typename PairStyle::device_type>*>::type list) {
+EV_FLOAT pair_compute_fullcluster (PairStyle* fpair, typename Kokkos::Impl::enable_if<(FULLCLUSTER&PairStyle::EnabledNeighFlags) != 0, NeighListKokkos<typename PairStyle::device_type>*>::type list) {
   EV_FLOAT ev;
   if(fpair->atom->ntypes > MAX_TYPES_STACKPARAMS) {
     typedef PairComputeFunctor<PairStyle,FULLCLUSTER,false,Specialisation >

**Comment by Pakketeretet2** [comment]
Nice find. Does gcc still accept such the with the -pedantic flag? If not,
that might be useful in the future. I forgot if that's enabled in the
kokkos makefile by default or not.

**Comment by stanmoore1** [comment]
@Pakketeretet2 The -pedantic flag is not enabled in the Kokkos Makefile by default. This should now be fixed and released.

**Comment by stanmoore1** [comment]
This is fixed in d9891abdf4d577707259288a86eb976099b34290.

**Comment by stanmoore1** [comment]
Now Kokkos mpi-only compiles with the stock OS X El Capitan version of g++ (Apple LLVM version 7.3.0), the fix is in the subversion branch.

**Comment by stanmoore1** [comment]
Actually the fix is in the local svn repo, will be in the subversion branch soon.
