### PR TITLE
Collected small changes and bugfixes for the next patch release

### LINKED ISSUE #1408: LAMMPS_BIGBIG problems in USER-REAXC
USER-REAXC uses the wrong print format for tagints in some places. First mentioned in #1405.

Compiler warnings:

    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp: In function ‘int Write_Init_Desc(reax_system*, control_params*, output_controls*, mpi_datatypes*)’:
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:289:58: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                  system->reax_param.sbp[ p_atom->type ].mass );
                                                              ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp: In function ‘int Write_Atoms(reax_system*, control_params*, output_controls*, mpi_datatypes*)’:
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:515:26: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                    p_atom->q );
                              ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:520:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                    p_atom->f[0], p_atom->f[1], p_atom->f[2], p_atom->q );
                                                                        ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:525:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                    p_atom->v[0], p_atom->v[1], p_atom->v[2], p_atom->q );
                                                                        ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:531:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                    p_atom->f[0], p_atom->f[1], p_atom->f[2], p_atom->q );
                                                                        ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp: In function ‘int Write_Bonds(reax_system*, control_params*, reax_list*, output_controls*, mpi_datatypes*)’:
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:613:48: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                        bo_ij->d, bo_ij->bo_data.BO );
                                                    ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:613:48: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘rc_tagint {aka long int}’ [-Wformat=]
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:619:64: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                        bo_ij->bo_data.BO_pi, bo_ij->bo_data.BO_pi2 );
                                                                    ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:619:64: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘rc_tagint {aka long int}’ [-Wformat=]
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp: In function ‘int Write_Angles(reax_system*, control_params*, reax_list*, reax_list*, output_controls*, mpi_datatypes*)’:
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:718:79: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘rc_tagint {aka long int}’ [-Wformat=]
                          system->my_atoms[k].orig_id, RAD2DEG( angle_ijk->theta ) );
                                                                                   ^
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:718:79: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘rc_tagint {aka long int}’ [-Wformat=]
    [...]/lammps/src/USER-REAXC/reaxc_traj.cpp:718:79: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘rc_tagint {aka long int}’ [-Wformat=]

### LINKED ISSUE #1410: [BUG] can't use logical NOT in atom variable
**Summary**

Using the logical NOT operator "!" inside an atom variable causes a "Invalid syntax in variable formula (../variable.cpp:2274)" error.

**LAMMPS Version and Platform**

Latest master version.

**Steps to Reproduce**

Run the following script:
```
atom_modify map yes
region box block -15 15 -15 15 -15 15
create_box 1 box
create_atoms 1 single 0 0 0

variable evar equal !0
print "This works: ${evar}"
variable avar atom 1
variable evar equal v_avar[1]
print "This also works: ${evar}"
variable avar atom !0
print "This should also work: ${evar}"
```

**Expected Behavior**

Expected output:
> This works: 1
> This also works: 1
> This should also work: 1

**Actual Behavior**

The actual output:
> This works: 1
> This also works: 1
> ERROR: Variable avar: Invalid syntax in variable formula (../variable.cpp:2274)
> Last command: This should also work: ${evar

**Further Information, Files, and Links**

All the other logical operators appear to work correctly with atom variables. Maybe it's because it is the only unary operator?

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

Collection of various small changes that don't warrant being reviewed as individual pull requests.

**Related Issues**

closes #1405 
closes #1408 
closes #1410 
closes #1412 
closes #1413 

**Author(s)**

Axel Kohlmeyer (Temple U)
Risto Toijala (University of Helsinki)
Evangelos Voyiatzis
Ryan Elliot (UMN)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

n/a

**Implementation Notes**

The following individual changes are included:
- print specific error message when trying to access local data from a compute via indexing
- update of plumed support to plumed 2.5.1. some corrections and bugfixes for Install.py and CMake
- update code to use TAGINT_FORMAT where "%d" or "%i" was used on `tagint` data. #1405 
- change format macros in USER-REAXC to use TAGINT_FORMAT for outputting atomIDs
- print warning when atom tags are too large for reax/c internal output
- error exit when the total number of atoms is too large for reax/c styles
- use `utils::strmatch()` for more accurate matching for styles to avoid not matching suffix style with strcmp() or matching the wrong styles with strstr()
- handle unary not "!" correctly in atom style variables and not only equal style variables
- add information about COMPASS to molecular force field HOWTO section. PR #1412 
- pair style kim off-by-one error bugfix, PR #1413

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

File: src/USER-COLVARS/fix_colvars.cpp [hunk 1]
```diff
@@ -645,7 +645,7 @@ void FixColvars::setup(int vflag)
 /* ---------------------------------------------------------------------- */
 /* Main colvars handler:
  * Send coodinates and add colvar forces to atoms. */
-void FixColvars::post_force(int vflag)
+void FixColvars::post_force(int /*vflag*/)
```
Comment (giacomofiorin) [inline src/USER-COLVARS/fix_colvars.cpp]: Had these changes already in the Colvars repo, but thanks for making sure.

File: src/USER-REAXC/reaxc_traj.h [hunk 2]
```diff
@@ -42,7 +42,7 @@
 #define SCI_LINE  "%-37s%-24g\n"
 #define REAL3_LINE "%-32s%9.3f,%9.3f,%9.3f\n"
 
-#define INIT_DESC "%9d%3d%9s%10.3f\n" //AtomID - AtomType, AtomName, AtomMass
+#define INIT_DESC TAGINT_FORMAT "%3d%9s%10.3f\n" //AtomID - AtomType, AtomName, AtomMass
```
[the remark this answers is not in the document]
Comment (akohlmey) [reply src/USER-REAXC/reaxc_traj.h]: good point. i'll do this differently. when looking closer, then this looks like it is trying to emulate some fortran style output, but the fixed buffer size will be missing blanks for atom IDs of 1 billion and overflow for atom IDs 10x larger. Similar for positions in very large boxes, it will be missing blanks for position values over 1000000 and under -100000, and overflow for 10x larger in magnitude.

**Comment by rtoijala** [comment]
With GCC 5.4.0, this no longer compiles since commit 50427ce05df76592752414c7c22194f245a112bb  due to syntax errors in hashlittle.cpp. I suggest either adding `&& __GNUC__ >= 7` to the check for enabling the fallthrough attribute, or just using the `/* fall through */` comment syntax that is used elsewhere in the file (and should be recognized by GCC).

    [...]/lammps/src/hashlittle.cpp: In function ‘uint32_t hashlittle(const void*, size_t, uint32_t)’:
    [...]lammps/src/hashlittle.cpp:30:23: error: expected primary-expression before ‘__attribute__’
     #define _fallthrough  __attribute__ ((fallthrough))
                           ^
    [...]/lammps/src/hashlittle.cpp:304:40: note: in expansion of macro ‘_fallthrough’
         case 12: c+=((uint32_t)k[11])<<24; _fallthrough;
                                            ^
etc... The same for each `_fallthrough`.

**Comment by akohlmey** [comment]
> With GCC 5.4.0, this no longer compiles since commit [50427ce](https://github.com/lammps/lammps/commit/50427ce05df76592752414c7c22194f245a112bb) due to syntax errors in hashlittle.cpp. I suggest either adding `&& __GNUC__ >= 7` to the check for enabling the fallthrough attribute, or just using the `/* fall through */` comment syntax that is used elsewhere in the file (and should be recognized by GCC).

a comment is apparently not recognized by current GCC. i've tried several variants, including those from the GCC documentation. i refuse to make these ifdefs compiler version specific (just had a similar issue with the upcoming GCC 9 changing their interpretation/implementation of the OpenMP sharing clause requirements for const variables without indicating it in a compiler neutral way or having some grace period where both, old and new variant is accepted). since this is simply about a silly warning. i'd rather have the warning. 383e206cc22fd91f0ed30318b9c8cd0055b8ab42 prints the warning on my machine, despite the comment. it is still good to have the comments to indicate it is intentional.

**Comment by akohlmey** [comment]
> I approve and approve.

thanks. i'll merge it only once, though. :smile:
