### PR TITLE
Fix bugs in handling of local pair property computes with hybrid pair styles

### LINKED ISSUE #1675: [BUG] user documentation of the user-h5md package
in https://lammps.sandia.gov/doc/Build_extras.html#user-h5md-package ,the traditional make"
make lib-h5md                     # print help message
make lib-hm5d args="-m h5cc"      # build with h5cc compiler" is wrong, shouled be '
make lib-h5md
make lib-h5md args="-m h5cc" '

### LINKED ISSUE #1676: memory.cpp fails compilation under Intel 17.0.1.132, IMPI 2017.1.132.
**Summary**
     Compilation fails on memory.cpp with error pasted under Actual Behavior.
**LAMMPS Version and Platform**
     7Aug19, CentOS7, Skylake.
**Expected Behavior**
     Successful compilation.
**Actual Behavior**
     Compilation fails with diagnostic ...
```
   ../memory.cpp(88): error: identifier "memcpy" is undefined
         memcpy(ptr, optr, MIN(nbytes,malloc_usable_size(optr)));
         ^
   compilation aborted for ../memory.cpp (code 2)
```
**Steps to Reproduce**
     Compile with Intel 17.0.1.132, IMPI 2017.1.132.
**Further Information, Files, and Links**
     Have proposed change to code in branch patch-1.  Adds ```#include <cstring>```.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

The processing of `Pair::svector` data in hybrid pair styles was using nested loops with the same loop variable and thus only worked by chance. Also when multiple pair styles supported extra data, the output would be overwritten and truncated to the shortest list. Now we get all properties appended for all active pair styles for a given pair of atom types and the list is padded with zeros.

This also fixes a couple of minor bugs found along the way. Closes #1675 and closes #1676 

**Related Issues**

The nested loop bug was reported on the [lammps-users mailing list](https://sourceforge.net/p/lammps/mailman/message/36756448/)

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This changes the behavior of how custom properties (p1, p2, p3, ... pN) are handled with compute `pair/local`, but since the original behavior was broken and only worked by accident, there is no major change. The cases, that previously worked (only one sub-style supports extra data) should produce the same output.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

File: doc/src/compute_pair_local.txt [hunk 1]
```diff
@@ -62,7 +62,10 @@ pair styles do not define any additional quantities, so N = 0.  An
 example of ones that do are the "granular pair styles"_pair_gran.html
 which calculate the tangential force between two particles and return
 its components and magnitude acting on atom I for N = 1,2,3,4.  See
-individual pair styles for details.
+individual pair styles for details. When using hybrid pair styles,
```
Comment (sjplimp) [inline doc/src/compute_pair_local.txt]: I think this sentence is confusing.  How about something like this:

If one of the "pair_style hybrid"_pair_hybrid.html commands is being used,
then {pN} will be the sum of contributions from any pair sub-styles which define it
and which are active for the particular pairwise interaction (based on the atom
types of the 2 atoms).

Comment (akohlmey) [reply doc/src/compute_pair_local.txt]: this is not correct. it never was the sum (things were just copied over) and it cannot be the sum, since the different pair styles may store very different properties in that vector and particularly those may be properties that may not make sense if summed. the modified code will contain the "combined" list of properties, i.e. those of the first pair style, then followed by the second (active) pair style and so on and then padded with zeros in case not all pair styles are active for a given pair of atom types.

Comment (sjplimp) [reply doc/src/compute_pair_local.txt]: Then I'm still confused what you mean by combined and padding.  Say the user specifies p2, and
there are 4 sub-styles in the PH comand, only 3 of which apply to types 1,2, and only 2 of the 3 compute a p2.  Then what is the output?  4 values, 3 values, some of them zero, which ones? I agree it's complicated.  I just don't think any of these doc sentences are clear to the user.  Maybe an example or 2 is needed, so it's not just words.

Comment (akohlmey) [reply doc/src/compute_pair_local.txt]: There are two problems: a) pair style hybrid and hybrid/overlay use the same function and b) you cannot just sum the output, since those could be very different properties. the unchanged code just copies properties over, but only up to the minimum number of extra properties. The more i think about it, the more it seems better to change a) and have a different function for hybrid and hybrid/overlay. For style hybrid the data from whatever the active pair style is would be copied over and then padded with zeros so that the number of total entries is the maximum of whatever the different pair styles support. if a pair style has no added data those would be all zeros.  for style hybrid/overlay, the output would be the concatenated list of all vectors from all pair styles (i.e. its length would be the sum of the lengths of the individual pair styles) and the data would be replaced by zeros, if a pair style is not active for a given pair of atom types. Right now, it outputs only the active pair styles, so for hybrid/overlay outputting p2 would be p2 of the first active pair style, thus it could be a different property depending on which pair styles are active. for hybrid, the output would be the same, i.e. p2 would be p2 for whatever pair style is active, since there can only be one active pair style.

Comment (sjplimp) [reply doc/src/compute_pair_local.txt]: Hmmm - this is getting more complicated.  What if we augment the syntax of the requested field, something like p2/n, where n = the index (1 to N) of the pair hybrid sub-style.  I think we've done something similar for other commands that work with pair hybrid sub-styles?

In this case it would mean the p2 value of the Nth sub-style.  Make it an error if that sub-style does not provide a p2 (can we detect that?)  Use a value of 0.0 if the sub-style is not defined for the atom types of I,J (so that the user would just see non-zero and zero values in a big list of compute pair/local output).  If the user wants to get multiple values from a sub-style, they can just list multiple fields in the pair/local command, e.g. p2/1, p2/2, p2/3.  This way a single field always means a single value.  No padding, no difference between hybrid and hybrid/overlay.

Comment (akohlmey) [reply doc/src/compute_pair_local.txt]: i don't see how this can be done without an ugly hack in compute pair/local, i.e. that compute pair/local has to detect, whether it is accessing a hybrid or hybrid/local pair style and then use the more complex syntax. the implementation in pair style hybrid or hybrid/overlay could then be set up uniformly as i had outlined it for pair style hybrid/overlay and compute pair local would need to query the individual substyles of pair style hybrid, how many extra data elements the single function would provide.
considering, that this is quite a corner case as it is, and that there are very few pair styles that support this feature, i would leave compute pair/local alone and have people count out how many entries there are. the one person on lammps-users, that what reporting the bug would be ok with having the various lists of properties appended to each other

File: doc/src/compute_pair_local.txt [hunk 2]
```diff
@@ -62,7 +62,17 @@ pair styles do not define any additional quantities, so N = 0.  An
 example of ones that do are the "granular pair styles"_pair_gran.html
 which calculate the tangential force between two particles and return
 its components and magnitude acting on atom I for N = 1,2,3,4.  See
-individual pair styles for details.
+individual pair styles for details. When using pair style {hybrid},
```
[the remark this answers is not in the document]
Comment (akohlmey) [reply doc/src/compute_pair_local.txt]: docs are updated. fixed a few typos and made it read a little better.

**Comment by akohlmey** [comment]
@sjplimp anything still missing here?

**Comment by sjplimp** [comment]
good to go
