### ISSUE TITLE
[BUG] 24Aug2020 fails to build with kokkos-3.2.00: error: expected '(' for function-style cast or type construction

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#2372]
```
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/atom.cpp:21:
In file included from /wrkdirs/usr/ports/science/lammps/work/.build/styles/style_atom.h:2:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/atom_vec_angle_kokkos.h:25:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/atom_vec_kokkos.h:18:
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/kokkos_type.h:232:55: error: expected '(' for function-style cast or type construction
  enum {value = Kokkos::Experimental::ScatterNonAtomic};
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/kokkos_type.h:272:59: error: expected '(' for function-style cast or type construction
  enum {value = Kokkos::Experimental::ScatterNonDuplicated};
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/kokkos_type.h:297:25: error: template argument for non-type template parameter must be an expression
class ScatterViewHelper<Kokkos::Experimental::ScatterDuplicated,T1,T2> {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/kokkos_type.h:293:14: note: template parameter is declared here
template<int value, typename T1, typename T2>
             ^
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/kokkos_type.h:306:25: error: template argument for non-type template parameter must be an expression
class ScatterViewHelper<Kokkos::Experimental::ScatterNonDuplicated,T1,T2> {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_24Aug2020/src/KOKKOS/kokkos_type.h:293:14: note: template parameter is declared here
template<int value, typename T1, typename T2>
             ^
4 errors generated.
*** Error code 1
```

clang-8
FreeBSD 12.2

Perhaps c++11 isn't sufficient?

Log: http://beefy6.nyi.freebsd.org/data/121amd64-default/548692/logs/errors/lammps-2020.08.24.log

**Comment by stanmoore1** [comment]
This compiles fine for me on RHEL with clang-9.0.

**Comment by akohlmey** [comment]
As it so happens, I was just testing building the current master branch of LAMMPS and running the included unittests and building the html and pdf documentation on a FreeBSD 12.1 virtual machine today. There are some minor tweaks and adjustments coming, but the KOKKOS package (for OpenMP) builds just fine with the (native) Clang 8 compiler. Also, I am regularly compiling with Clang-10 on a Fedora 32 machine. So my suspicion would be that this is not a Kokkos (library or LAMMPS package) issue. At least not with the state of the latest development branch.
You may want to wait for the next patch release (tomorrow evening if everything works out) and try again.

**Comment by junghans** [comment]
Kokkos-3.2 support (#2311) is only part of the 24Aug2020 release, hence it doesn't build against an external kokkos-3.2, so you either need to patch it (like Fedora, see https://src.fedoraproject.org/rpms/lammps/blob/master/f/kokkos-3.2-support-PR-2311.patch) or wait for the next release as @akohlmey suggested.

**Comment by stanmoore1** [comment]
Ah, so Kokkos-3.2 support (#2311) in LAMMPS was merged on 26Aug2020, which is after the 24Aug2020, that must be the issue. The next patch should work.

**Comment by akohlmey** [comment]
New patch has just been released
