### ISSUE TITLE
memory.cpp fails compilation under Intel 17.0.1.132, IMPI 2017.1.132.

### ISSUE THREAD

**Issue by aaichsmn** [lammps/lammps#1676]
**Summary**
     Compilation fails on memory.cpp with error pasted under Actual Behavior.
**LAMMPS Version and Platform**
     7Aug19, CentOS7, Skylake.
**Expected Behavior**
     Successful compilation.
**Actual Behavior**
     Compilation fails with diagnostic ...
```
   ../memory.cpp(88): error: identifier "memcpy" is undefined
         memcpy(ptr, optr, MIN(nbytes,malloc_usable_size(optr)));
         ^
   compilation aborted for ../memory.cpp (code 2)
```
**Steps to Reproduce**
     Compile with Intel 17.0.1.132, IMPI 2017.1.132.
**Further Information, Files, and Links**
     Have proposed change to code in branch patch-1.  Adds ```#include <cstring>```.

**Comment by Pakketeretet2** [comment]
memcpy is typically defined in string.h/cstring, but it's hard to tell
whether or not that is indirectly included or not. Will it compile if you
directly include cstring in memory.cpp?

**Comment by rbberger** [comment]
@Pakketeretet2 Axel already has the fix here: ca301f0

**Comment by Pakketeretet2** [comment]
@rbberger Oops, I'm not fully awake yet.

**Comment by aaichsmn** [comment]
Compiled and ran tests O.K.  Still testing here but looks good so far.

                                                                Best regards,
                                                                Phil

                                                                P. A. Cheeseman, Ph.D.
                                                                Senior Scientific Applications Analyst
                                                                Rosen Center for Advanced Computing
                                                                aai@purdue.edu
                                                                765.496.8224
                                                                www.purdue.edu/itap

**Comment by aaichsmn** [comment]
O.K.  I just checked the source in the master branch and didn't see cstring included so I submitted my change.  I'd downloaded lammps-stable.tar.gz from https://lammps.sandia.gov/cgi-bin/download.pl.

     Thanks for your time on this.

                                                                Best regards,
                                                                Phil

                                                                P. A. Cheeseman, Ph.D.
                                                                Senior Scientific Applications Analyst
                                                                Rosen Center for Advanced Computing
                                                                aai@purdue.edu
                                                                765.496.8224
                                                                www.purdue.edu/itap

**Comment by akohlmey** [comment]
> O.K. I just checked the source in the master branch and didn't see cstring included so I submitted my change. I'd downloaded lammps-stable.tar.gz from https://lammps.sandia.gov/cgi-bin/download.pl. Thanks for your time on this.

the commit @rbberger was referring to is in a pending pull request that has not yet been merged.
you cannot download the development code from the sandia website, the development version will be updated with each patch release, and the stable package will only be updated on every stable release (typically, every 3-4 months).
besides, when compiling with intel compilers, you should also enable using TBB (which is usually bundled with the compiler package) and then this issue will not appear anyway.

BTW: there is no PR submission from you.

**Comment by aaichsmn** [comment]
Thanks for the tip.  I navigated away from the edit screen w/o clicking the green button.

     Am reading further into your documentation about how to do it right if there is a next time.

                                                                Happy Friday,
                                                                Phil

                                                                P. A. Cheeseman
                                                                aai@purdue.edu
                                                                765.496.8224
