### ISSUE TITLE
Cannot build with -DLAMMPS_EXCEPTIONS in 22Feb2018

### ISSUE THREAD

**Issue by ExpHP** [lammps/lammps#818]
## Summary

```
$ make rust mode=lib
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: Entering directory '/home/exp/dev/lammps/src/Obj_rust'
...
...
...
g++ -g -O3  -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -DLAMMPS_EXCEPTIONS  -I../STUBS     -c ../fix_wall.cpp
g++ -g -O3  -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -DLAMMPS_EXCEPTIONS  -I../STUBS     -c ../library.cpp
g++ -g -O3  -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -DLAMMPS_EXCEPTIONS  -I../STUBS     -c ../reader.cpp
../library.cpp: In function ‘void lammps_commands_string(void*, char*)’:
../library.cpp:65:11: error: redeclaration of ‘LAMMPS_NS::Error* error’
   Error * error = lmp->error; \
           ^
../library.cpp:292:3: note: in expansion of macro ‘BEGIN_CAPTURE’
   BEGIN_CAPTURE
   ^~~~~~~~~~~~~
../library.cpp:65:11: note: ‘LAMMPS_NS::Error* error’ previously declared here
   Error * error = lmp->error; \
           ^
../library.cpp:279:3: note: in expansion of macro ‘BEGIN_CAPTURE’
   BEGIN_CAPTURE
   ^~~~~~~~~~~~~
```

## LAMMPS Version (Bug Report)

The bug affects the February 22 2018 release and the current master (as of Feb 25), and appears to have been introduced by commit 378c5071bf8668c0a199ce53bcea915109f248f3 by @akohlmey .  By having two `{BEGIN,END}_CAPTURE` blocks in the same scope, the variable `error` gets defined twice.

Even if this compiler error was superficially resolved by, say, changing  `BEGIN_CAPTURE` to enclose its entire expansion in braces (to limit the scope of `error`), the behavior in 378c5071bf8668c0a199ce53bcea915109f248f3 would still not appear to be correct to me without further tweaking, because the function does not actually return if an error occurs inside the [`CAPTURE` block on lines 279-284](https://github.com/lammps/lammps/blob/378c5071bf8668c0a199ce53bcea915109f248f3/src/library.cpp#L279-L284).

## Steps to Reproduce (Bug Report)

1. Take Makefile.serial, copy to MINE/Makefile.mine
2. Append `-DLAMMPS_EXCEPTIONS` to the end of the `LMP_INC` line.
3. `make mode=lib`

**Comment by ExpHP** [comment]
Ah, go figure, no sooner do I post this then I find [this PR](https://github.com/lammps/lammps/pull/815).  IT appears @akohlmey is already on it.

**Comment by akohlmey** [comment]
@ExpHP the behavior in 378c5071bf8668c0a199ce53bcea915109f248f3 *is* correct (except for the pointer redeclaration issue) since `Error::all()` will throw a `LAMMPSException` in case you compile LAMMPS with `-DLAMMPS_EXCEPTIONS`.

**Comment by ExpHP** [comment]
@akohlmey but it seems to me that these exceptions will [get caught in `END_CAPTURE`](https://github.com/lammps/lammps/blob/378c5071bf8668c0a199ce53bcea915109f248f3/src/library.cpp#L78-L80), which sets the error state for the C API, and does not appear to return. Is this not correct? Since the exception gets caught, execution should resume beginning from `END_CAPTURE` on line [284](https://github.com/lammps/lammps/blob/378c5071bf8668c0a199ce53bcea915109f248f3/src/library.cpp#L284).

Hmm.  On a similar note, now that I am looking more closely at it, it seems to me that [the upcoming PR](https://github.com/lammps/lammps/pull/815) may potentially perform `delete [] copy` twice when `LAMMPS_EXCEPTIONS` is enabled. (lines 288 and 311)

**Comment by akohlmey** [comment]
@ExpHP looks like you are not reading my changes in the commit correctly. Have a look at the modified subroutine at https://github.com/akohlmey/lammps/blob/58e01a9eee0b700a807da11cf3f4bb130c74e8a3/src/library.cpp#L275
i also don't see how it should be possible to execute `delete[] copy` twice.

**Comment by ExpHP** [comment]
Running the preprocessor on the file in 58e01a9eee0b700a807:

```
gcc -DLAMMPS_EXCEPTIONS -Isrc/STUBS -E src/library.cpp
```

```c++
void lammps_commands_string(void *ptr, char *str)
{
  LAMMPS *lmp = (LAMMPS *) ptr;



  int n = strlen(str) + 1;
  char *copy = new char[n];
  strcpy(copy,str);

  Error * error = lmp->error; try
  {
    if (lmp->update->whichflag != 0) {
      delete [] copy;
      lmp->error->all("src/library.cpp",289,"Library error: issuing LAMMPS command during run");
    }

    char *ptr = copy;
    for (int i=0; i < n-1; ++i) {


      if ((copy[i] == '&') && (copy[i+1] == '\n'))
        copy[i+1] = copy[i] = ' ';
      else if ((copy[i] == '&') && (copy[i+1] == '\0'))
        copy[i] = ' ';

      if (copy[i] == '\n') {
        copy[i] = '\0';
        lmp->input->one(ptr);
        ptr = copy + i+1;
      } else if (copy[i+1] == '\0')
        lmp->input->one(ptr);
    }
  }
  catch(LAMMPSAbortException & ae) { int nprocs = 0; MPI_Comm_size(ae.universe, &nprocs ); if (nprocs > 1) { error->set_last_error(ae.message.c_str(), ERROR_ABORT); } else { error->set_last_error(ae.message.c_str(), ERROR_NORMAL); } } catch(LAMMPSException & e) { error->set_last_error(e.message.c_str(), ERROR_NORMAL); }

  delete [] copy;
}
```

Reformatting and trimming out the irrelevant parts...

```c++
void lammps_commands_string(void *ptr, char *str)
{
  LAMMPS *lmp = (LAMMPS *) ptr;

  int n = strlen(str) + 1;
  char *copy = new char[n];
  strcpy(copy,str);

  Error * error = lmp->error;
  try {
    if (lmp->update->whichflag != 0) {
      delete [] copy;  // <-- (((1)))
      lmp->error->all("src/library.cpp",289,"Library error: issuing LAMMPS command during run");
    }

    ...
  }
  catch(LAMMPSAbortException & ae) {
    ...
  }
  catch(LAMMPSException & e) {
    error->set_last_error(e.message.c_str(), ERROR_NORMAL); // <---  (((2)))
  }

  delete [] copy; // <-- (((3)))
}
```

After the `delete [] copy` marked "1" occurs, a `LammpsException` is thrown and then caught at the line marked "2". and then it continues onto the `delete [] copy` at the line marked "3"

**Comment by akohlmey** [comment]
@ExpHP Thanks for your explanation and patience. You are correct. I'll change the code accordingly.
