### ISSUE TITLE
Build with Python-3.7 broken

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#975]
## Summary

Building version 16Mar2018 on Fedora Rawhide with python-3.7 fails

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

```
builddir/build/BUILD/lammps-stable_16Mar2018/src/PYTHON/python_compat.h:30:48: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PY_STRING_AS_STRING(X) PyUnicode_AsUTF8(X)
                                ~~~~~~~~~~~~~~~~^~~
```
## LAMMPS Version (Bug Report)

16Mar2018

## Expected Behavior (Bug Report)

Builds

## Actual Behavior (Bug Report)

Build error

## Steps to Reproduce (Bug Report)

On a fedora system `fedpkg build --target=f29-python`

## Further Information, Files, and Links

[Build log](https://github.com/lammps/lammps/files/2147290/build.log.txt)

**Comment by junghans** [comment]
Fixed by #979

**Comment by junghans** [comment]
https://src.fedoraproject.org/rpms/lammps/c/7713b2c0c12f8b3d15d3814b211310f79d87cf6d?branch=master
