### ISSUE TITLE
Wrong const-ness deduced in Parallel_for(?)

### ISSUE THREAD

**Issue by Pakketeretet2** [lammps/lammps#1045]
## Summary

It seems like the kokkos::parallel_for construct fails to identify the proper operator[] to use on Few<double,3> in fix_momentum_kokkos.cpp. 
I made the title as descriptive as possible but I can only guess as to what is going on.

## Type of Issue

Bug report

## Detailed Description (Enhancement Suggestion)

When trying to build LAMMPS with the new CMake build system, the build fails on the source file related to fix momentum, which seems strange. The only difference I can think of is that the CMake build also attempts to compile Kokkos for Device=Serial, whereas the Makefile-based build does not.
Here is the shortest sample of such offending code (lines 109 to 133 in https://github.com/lammps/lammps/blob/master/src/KOKKOS/fix_momentum_kokkos.cpp).

```cpp
  // ...
  auto groupbit2 = groupbit;
  if (linear) {
    /* this is needed because Group is not Kokkos-aware ! */
    atomKK->sync(ExecutionSpaceFromDevice<LMPHostType>::space,
        V_MASK | MASK_MASK | TYPE_MASK | RMASS_MASK);
    Few<double, 3> vcm;
    group->vcm(igroup,masstotal,&vcm[0]);

    // adjust velocities by vcm to zero linear momentum
    // only adjust a component if flag is set

    auto xflag2 = xflag;
    auto yflag2 = yflag;
    auto zflag2 = zflag;

    Kokkos::parallel_for(nlocal, LAMMPS_LAMBDA(int i) {
      if (mask(i) & groupbit2) {
        if (xflag2) v(i,0) -= vcm[0];
        if (yflag2) v(i,1) -= vcm[1];
        if (zflag2) v(i,2) -= vcm[2];
      }
    });
    atomKK->modified(execution_space, V_MASK);
  }
  // ...
```

The compiler chokes with the following types of errors:
```bash
/home/stefan/projects/lammps-mine/src/KOKKOS/fix_momentum_kokkos.cpp:127:28: error: passing ‘const Few<double, 3>’ as ‘this’ argument discards qualifiers [-fpermissive]
         if (xflag2) v(i,0) -= vcm[0];
In file included from /home/stefan/projects/lammps-mine/src/KOKKOS/domain_kokkos.h:19,
                 from /home/stefan/projects/lammps-mine/src/KOKKOS/fix_momentum_kokkos.cpp:20:
/home/stefan/projects/lammps-mine/src/KOKKOS/kokkos_few.h:54:29: note:   in call to ‘T& Few<T, n>::operator[](std::size_t) [with T = double; long unsigned int n = 3; std::size_t = long unsigned int]’
   KOKKOS_INLINE_FUNCTION T& operator[](std::size_t i) {
                             ^~~~~~~~
```
(and the same for vcm[1], vcm[2], xcm[0..2] and omega[0..2].)

Hence, it seems that KOKKOS is convinced it should be using the non-const variant of operator[] inside the parallel_for, but it cannot because vcm inside the parallel_for is const. The strangest part is that if I explicitly "cast" vcm to a constant reference the code compiles, i.e.:
```
    const Few<double,3> &vcm_ref = vcm;

    Kokkos::parallel_for(nlocal, LAMMPS_LAMBDA(int i) {
      if (mask(i) & groupbit2) {
        if (xflag2) v(i,0) -= vcm_ref[0];
        if (yflag2) v(i,1) -= vcm_ref[1];
        if (zflag2) v(i,2) -= vcm_ref[2];
      }
    });
    atomKK->modified(execution_space, V_MASK);
  }
```

@junghans @stanmoore1 

## LAMMPS Version (Bug Report)

August 2, 2018.
For what it's worth: I am running on Arch Linux and trying to compile with the GNU C++ compiler version 8.1.1.

## Expected Behavior (Bug Report)

I would expect the CMake version of lammps to just build without the weird modification I added.

## Actual Behavior (Bug Report)

The build fails with errors as shown above.

## Steps to Reproduce (Bug Report)

1. Make a new directory for a CMake build in the lammps directory: 
$ cd lammps
$ mkdir build_cmake
$ cd build_cmake
2. Configure cmake:
(I enabled PKG_{BODY,GPU,KOKKOS,KSPACE,MANYBODY,MC,MISC,MOLECULE,PYTHON,REPLICA,RIGID,SRC,USER-{CGDNA,COLVARS,FEP,MANIFOLD,MISC,VORONOI}}.)
$ ccmake ../cmake
3. Try to build:
$ make

## Further Information, Files, and Links

The attached patch mitigates the error in the sense that it compiles, but it hardly seems like the right solution to the problem. At the end I run into a linker error because CMake does not seem to find the kokkos library but that is a separate issue.

[fix_momentum_kokkos_patch.txt](https://github.com/lammps/lammps/files/2270975/fix_momentum_kokkos_patch.txt)

**Comment by rbberger** [comment]
Confirmed with GCC 8.1.0 on Fedora 28 and Arch with GCC 8.2.0
